#! /usr/bin/env python
# helper function library

import os
# get everything from a folder but the README.md file
def get_folders(dir):
    for item in os.listdir(dir):
        if os.isdir(item):
            print(item)
    return list(filter(lambda item: True, os.listdir(dir)))
